### ISSUE TITLE
File Importer

### ISSUE THREAD

**Issue by JamesSedlacek** [SwiftfulThinking/SwiftfulRouting#14]
It'd be nice to have the ability to present this kind of screen using this framework to keep everything I present within the ViewModel.

https://developer.apple.com/documentation/swiftui/list/fileimporter(ispresented:allowedcontenttypes:allowsmultipleselection:oncompletion:)

**Comment by SwiftfulThinking** [comment]
I moved this to Discussions thread (https://github.com/SwiftfulThinking/SwiftfulRouting/discussions/16).
