### ISSUE TITLE
i found a display error with my iphonex  

### ISSUE THREAD

**Issue by SnailLoveSmile** [SwiftfulThinking/SwiftfulRouting#27]
![WechatIMG272](https://github.com/SwiftfulThinking/SwiftfulRouting/assets/33648940/5a572a31-6141-457e-8241-0e451a7d02cf)

if sheetDetents  height(demo`s height is 750)  is more than a number tis will appear

**Comment by SwiftfulThinking** [comment]
The 750 is only part of the sample project. The developer can user a smaller number when building for smaller devices. I don't think the framework should handle this internally.
