### ISSUE TITLE
Hoping to get a clear example of the following please.

### ISSUE THREAD

**Issue by waelsaad** [SwiftfulThinking/SwiftfulRouting#33]
Hi Nick @SwiftfulThinking thank you for the update and this library. I know the framework is capable of this as I can see some of the possibilities from the demo but I was still confused and I couldn't get the following to work especially with MVVM. iOS 16 NavigationStack.

WelcomeScene -> ULA - Sheet (Once accepted terms -> Dismiss) -> PinScene (FullscreenCover) -> Push to Home. -> SettingsScene (FullCover) Then Logout button to go back to PinScene.

**Comment by SwiftfulThinking** [comment]
Thanks for the comment. The flow your describing isn't something that the current released version of this package or the SwiftUI framework supports out-of-the-box. If you use this package, you'd still need to manage some local State the same way you'd do it without the package.

However, this will be supported in version 6.0 via `transitionModule` (https://github.com/SwiftfulThinking/SwiftfulRouting/releases/tag/beta-6.0).

Closing ticket per above!
