### ISSUE TITLE
dismissScreenStack working from root screen only once

### ISSUE THREAD

**Issue by edementiev** [SwiftfulThinking/SwiftfulRouting#60]
I needs to realise  the functionality make possibility close all child screens in screen stack by event

The best way it's to make a catch an event on the root screen and call router.dismissScreenStack() from the root view

The first call is working properly, but the second call of router.dissmissScreenStack() and any another not working with error:
🕊️ SwiftfulRouting 🕊️ -> Failed to dismiss screens screenStack. Could not find user's active screens.

Could you, please release the functionality to dissmiss the screens stack from root screen, not only from top screen in stack

**Comment by SwiftfulThinking** [comment]
Hi, maybe it is a problem with your implementation? When I use the [Sample project](https://github.com/SwiftfulThinking/SwiftfulRoutingExample), I can dismissScreenStack multiple times and it is working as expected. 

Can you provide sample code for your problem?

**Comment by edementiev** [comment]
Sure, becouse the call dismissScreenStack() in your example project calling from the top level screen in navigation stack.

In my project i needs dismiss all screens in stack by tapping in tab bar button. By this reasone i needs call the dismissScreenStack() from main (bottom) screen in navigation stack. In this case the first call is working propertly, but second call does not working.

Please find the example code in the attached archive.
The button "Call dissmissScreenStack()" imitates the tabbar with one tab )

Please make the text steps:
1. Tap "Open detailedView" on the main screen
2. Tap on "Call dismissScreenStack()" button
3. See the dismissScreenStack() is working propertly
4. Tap "Open detailedView" again
5. Tap on "Call dismissScreenStack()" button
6. dissmissScreenStack() dows not working and we get the error message on the log

[DismissScreenStack.zip](https://github.com/SwiftfulThinking/SwiftfulRouting/files/15298966/DismissScreenStack.zip)

**Comment by Suri1044** [comment]
HI @SwiftfulThinking : Can you look into this issue plz. As said by @edementiev: This is not working for the second time. Hoping the solution soon.

**Comment by SwiftfulThinking** [comment]
Thanks @edementiev for finding this bug and for the example project - it helped a lot. This is now fixed in release [5.3.5](https://github.com/SwiftfulThinking/SwiftfulRouting/releases/tag/5.3.5).

Feel free to re-open this issue if the problem persists 🤙
