### ISSUE TITLE
Determine whether a page is in the navigation path

### ISSUE THREAD

**Issue by CoderLGL** [SwiftfulThinking/SwiftfulRouting#79]
Thank you for creating and sharing SwiftfulRouting—it’s a fantastic library! I have a question regarding its functionality:

In the context of managing navigation paths using SwiftfulRouting, is there a built-in way to determine whether a specific page (or route) is already present in the current navigation path? For instance, if I have a NavigationPath or some form of route tracking, I’d like to check if a certain page has already been pushed to avoid duplication.

If this feature isn’t available out-of-the-box, could you suggest the best approach to implement such functionality with the current library?

Looking forward to your guidance. Thanks again for your amazing work!

**Comment by SwiftfulThinking** [comment]
This is not available out of the box but I’m hoping to implement this next year.Fwiw, this isn’t supported in the native SwiftUI framework either. You’d have to track manually for now.Sent from my iPhoneOn Dec 4, 2024, at 2:29 AM, Guang ***@***.***> wrote:﻿
Thank you for creating and sharing SwiftfulRouting—it’s a fantastic library! I have a question regarding its functionality:
In the context of managing navigation paths using SwiftfulRouting, is there a built-in way to determine whether a specific page (or route) is already present in the current navigation path? For instance, if I have a NavigationPath or some form of route tracking, I’d like to check if a certain page has already been pushed to avoid duplication.
If this feature isn’t available out-of-the-box, could you suggest the best approach to implement such functionality with the current library?
Looking forward to your guidance. Thanks again for your amazing work!
